trigger:
- master

jobs:
- job: BuildWindowsWithSonarQube
  displayName: Build for Windows With SonarQube
  dependsOn: []
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: SonarQubePrepare@4
    inputs:
      SonarQube: 'Peach'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-cmake-windows-test'
      cliProjectName: 'geoffray-azure-cmake-windows-test'
      cliSources: 'src'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - pwsh: |
      $path = ".\build-wrapper-win-x86.zip"
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      (New-Object System.Net.WebClient).DownloadFile("https://peach.sonarsource.com/static/cpp/build-wrapper-win-x86.zip", $path)
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::ExtractToDirectory($path, ".")
      del $path
    displayName: Install buildwrapper
  - pwsh: |
      mkdir build
      cd build
      cmake ..
      cd ..
    displayName: Prepare build
  - bash: |
      build-wrapper-win-x86/build-wrapper-win-x86-64 --out-dir build_wrapper_output_directory cmake --build build/ --config Release
    displayName: Compile project in build wrapper
  - task: SonarQubeAnalyze@4

- job: BuildWindowsWithSonarCloud
  displayName: Build for Windows With SonarCloud
  dependsOn: []
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'geoffray-adde-sonarsource-github'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'geoffray-azure-cmake-windows-test'
      cliProjectName: 'geoffray-azure-cmake-windows-test'
      cliSources: 'src'
      extraProperties: 'sonar.cfamily.build-wrapper-output=build_wrapper_output_directory'
  - pwsh: |
      $path = ".\build-wrapper-win-x86.zip"
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      (New-Object System.Net.WebClient).DownloadFile("https://peach.sonarsource.com/static/cpp/build-wrapper-win-x86.zip", $path)
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      [System.IO.Compression.ZipFile]::ExtractToDirectory($path, ".")
      del $path
    displayName: Install buildwrapper
  - pwsh: |
      mkdir build
      cd build
      cmake ..
      cd ..
    displayName: Prepare build
  - bash: |
      build-wrapper-win-x86/build-wrapper-win-x86-64 --out-dir build_wrapper_output_directory cmake --build build/ --config Release
    displayName: Compile project in build wrapper
  - task: SonarCloudAnalyze@1